import type { AcademicYear, CalendarException, ISODate, ScheduleCycle, Section, SpecialScheduleOverride } from "../scheduling/types";
import { curriculumByCourse } from "../fixtures/curriculumPresets";
import { stAugustineAcademicYear, stAugustineClosures, stAugustineCycle, stAugustineDailyPeriods, stAugustineSpecialScheduleDates, teacherCourses, teacherPeriods } from "../fixtures/stAugustine2026";
import type { CurriculumUnit } from "../reality/reality";
export interface TeacherSectionConfig { period: string; courseName: string; meetingCycleLabels: string[]; }
export interface CRCConfig { schemaVersion:1; schoolName:string; academicYear:AcademicYear; cycle:ScheduleCycle; dailyPeriods:Record<string,string[]>; sections:TeacherSectionConfig[]; closures:CalendarException[]; specialScheduleDates:{date:ISODate;description:string}[]; specialScheduleOverrides:SpecialScheduleOverride[]; curriculum:Record<string,CurriculumUnit[]>; }
const copyCurriculum=()=>{const curriculum:Record<string,CurriculumUnit[]>={};for(const [name,preset] of Object.entries(curriculumByCourse))if(preset)curriculum[name]=preset.units.map(u=>({...u}));return curriculum;};
export function defaultStAugustineConfig():CRCConfig { return {schemaVersion:1,schoolName:"St. Augustine Preparatory School",academicYear:{...stAugustineAcademicYear},cycle:{...stAugustineCycle,labels:[...stAugustineCycle.labels]},dailyPeriods:Object.fromEntries(Object.entries(stAugustineDailyPeriods).map(([k,v])=>[k,[...v]])),sections:teacherPeriods.map(period=>({period,courseName:teacherCourses[period],meetingCycleLabels:Object.entries(stAugustineDailyPeriods).filter(([,ps])=>ps.includes(period)).map(([d])=>d)})),closures:stAugustineClosures.map(x=>({...x})),specialScheduleDates:stAugustineSpecialScheduleDates.map(x=>({date:x.date as ISODate,description:x.description})),specialScheduleOverrides:[],curriculum:copyCurriculum()}; }
export function stAugustineSchoolTemplate():CRCConfig { const c=defaultStAugustineConfig(); c.sections=[]; c.curriculum={}; return c; }
export function blankConfig():CRCConfig { return {schemaVersion:1,schoolName:"My School",academicYear:{name:"2026-2027",startDate:"2026-09-01",endDate:"2027-06-15",timeZone:"America/New_York"},cycle:{labels:["A","B"],rotationMode:"fixed_date",anchorDate:"2026-09-01",anchorCycleLabel:"A"},dailyPeriods:{},sections:[],closures:[],specialScheduleDates:[],specialScheduleOverrides:[],curriculum:{}}; }
export function validateConfig(config:CRCConfig):string[]{const errors:string[]=[];if(config.schemaVersion!==1)errors.push("Unsupported CRC file version.");if(!config.schoolName?.trim())errors.push("School name is required.");if(!config.academicYear?.startDate||!config.academicYear?.endDate)errors.push("Academic year start and end dates are required.");else if(config.academicYear.endDate<config.academicYear.startDate)errors.push("Academic year end date must be after start date.");if(!config.cycle?.labels?.length)errors.push("At least one rotation day is required.");if(config.cycle?.labels?.length&&new Set(config.cycle.labels).size!==config.cycle.labels.length)errors.push("Rotation day labels must be unique.");if(!config.cycle?.anchorDate)errors.push("A rotation anchor date is required.");if(config.cycle?.labels?.length&&!config.cycle.labels.includes(config.cycle.anchorCycleLabel))errors.push("Anchor cycle day must be one of the rotation labels.");if(!config.sections?.length)errors.push("At least one class section is required.");const seen=new Set<string>();for(const s of config.sections??[]){if(!s.period.trim()||!s.courseName.trim()||!s.meetingCycleLabels.length)errors.push(`Section ${s.period||"(unnamed)"} needs a period, course, and meeting days.`);if(seen.has(s.period.trim()))errors.push(`Period ${s.period} is listed more than once.`);seen.add(s.period.trim());for(const d of s.meetingCycleLabels)if(!config.cycle.labels.includes(d))errors.push(`Period ${s.period} uses unknown rotation day ${d}.`);}for(const x of config.closures??[])if(x.date<config.academicYear.startDate||x.date>config.academicYear.endDate)errors.push(`Closure ${x.date} is outside the academic year.`);return [...new Set(errors)];}
export function sectionFromConfig(section:TeacherSectionConfig):Section{return{id:`period-${section.period.toLowerCase()}`,courseName:section.courseName,sectionName:`Period ${section.period}`,periodCode:section.period,meetingCycleLabels:section.meetingCycleLabels};}
